/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddScheduledEmailReceiverRequest } from '../../models/add-scheduled-email-receiver-request';

export interface ApiScheduledEmailsIdReceiversPost$Params {
  id: string;
      body: AddScheduledEmailReceiverRequest
}

export function apiScheduledEmailsIdReceiversPost(http: HttpClient, rootUrl: string, params: ApiScheduledEmailsIdReceiversPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiScheduledEmailsIdReceiversPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiScheduledEmailsIdReceiversPost.PATH = '/api/ScheduledEmails/{id}/receivers';
