/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientContactDto } from '../../models/client-contact-dto';

export interface ApiClientCompaniesClientCompanyIdContactsGet$Plain$Params {
  clientCompanyId: string;
}

export function apiClientCompaniesClientCompanyIdContactsGet$Plain(http: HttpClient, rootUrl: string, params: ApiClientCompaniesClientCompanyIdContactsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClientContactDto>>> {
  const rb = new RequestBuilder(rootUrl, apiClientCompaniesClientCompanyIdContactsGet$Plain.PATH, 'get');
  if (params) {
    rb.path('clientCompanyId', params.clientCompanyId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClientContactDto>>;
    })
  );
}

apiClientCompaniesClientCompanyIdContactsGet$Plain.PATH = '/api/ClientCompanies/{clientCompanyId}/contacts';
