/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddClientContactRequest } from '../../models/add-client-contact-request';

export interface ApiClientCompaniesClientCompanyIdContactsPost$Plain$Params {
  clientCompanyId: string;
      body: AddClientContactRequest
}

export function apiClientCompaniesClientCompanyIdContactsPost$Plain(http: HttpClient, rootUrl: string, params: ApiClientCompaniesClientCompanyIdContactsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, apiClientCompaniesClientCompanyIdContactsPost$Plain.PATH, 'post');
  if (params) {
    rb.path('clientCompanyId', params.clientCompanyId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

apiClientCompaniesClientCompanyIdContactsPost$Plain.PATH = '/api/ClientCompanies/{clientCompanyId}/contacts';
