/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedResponseOfClientCompanyDto } from '../../models/paged-response-of-client-company-dto';

export interface ApiClientCompaniesGet$Json$Params {
  providerId?: string;
  page?: (number | string);
  pageSize?: (number | string);
}

export function apiClientCompaniesGet$Json(http: HttpClient, rootUrl: string, params?: ApiClientCompaniesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedResponseOfClientCompanyDto>> {
  const rb = new RequestBuilder(rootUrl, apiClientCompaniesGet$Json.PATH, 'get');
  if (params) {
    rb.query('providerId', params.providerId, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedResponseOfClientCompanyDto>;
    })
  );
}

apiClientCompaniesGet$Json.PATH = '/api/ClientCompanies';
