/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedResponseOfEmailAuditLogDto } from '../../models/paged-response-of-email-audit-log-dto';

export interface ApiEmailAuditLogsGet$Plain$Params {
  recipient?: string;
  success?: boolean;
  page?: (number | string);
  pageSize?: (number | string);
}

export function apiEmailAuditLogsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiEmailAuditLogsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedResponseOfEmailAuditLogDto>> {
  const rb = new RequestBuilder(rootUrl, apiEmailAuditLogsGet$Plain.PATH, 'get');
  if (params) {
    rb.query('recipient', params.recipient, {});
    rb.query('success', params.success, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedResponseOfEmailAuditLogDto>;
    })
  );
}

apiEmailAuditLogsGet$Plain.PATH = '/api/EmailAuditLogs';
