/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyActivityDto } from '../../models/daily-activity-dto';

export interface ApiDailyActivitiesIdGet$Json$Params {
  id: string;
}

export function apiDailyActivitiesIdGet$Json(http: HttpClient, rootUrl: string, params: ApiDailyActivitiesIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyActivityDto>> {
  const rb = new RequestBuilder(rootUrl, apiDailyActivitiesIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyActivityDto>;
    })
  );
}

apiDailyActivitiesIdGet$Json.PATH = '/api/DailyActivities/{id}';
