/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityStatus } from '../../models/activity-status';
import { DailyActivityDto } from '../../models/daily-activity-dto';

export interface ApiDailyActivitiesGet$Plain$Params {
  partnerId?: string;
  title?: string;
  theme?: string;
  status?: ActivityStatus;
  date?: string;
  page?: (number | string);
  pageSize?: (number | string);
}

export function apiDailyActivitiesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiDailyActivitiesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DailyActivityDto>>> {
  const rb = new RequestBuilder(rootUrl, apiDailyActivitiesGet$Plain.PATH, 'get');
  if (params) {
    rb.query('partnerId', params.partnerId, {});
    rb.query('title', params.title, {});
    rb.query('theme', params.theme, {});
    rb.query('status', params.status, {});
    rb.query('date', params.date, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DailyActivityDto>>;
    })
  );
}

apiDailyActivitiesGet$Plain.PATH = '/api/DailyActivities';
