/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactType } from '../models/contact-type';
export interface ClientContactDto {
  email: string;
  id: string;
  name: string;
  type: ContactType;
}
