/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportFrequency } from '../models/report-frequency';
export interface CreateScheduledEmailRequest {
  cronExpression: string;
  frequency: ReportFrequency;
  groupId: string;
  name: string;
  specificDayOfMonth: (number | string | null);
}
