/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateGroupRequest {
  clientCompanyId: string;
  groupLeaderId: string;
  name: string;
  projectId: string;
  timezone: string;
}
