/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailAuditLogDto {
  body: string;
  errorMessage: (string | null);
  id: string;
  recipient: string;
  sentAt: string;
  subject: string;
  success: boolean;
}
