/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmailAuditLogDto } from '../models/email-audit-log-dto';
export interface PagedResponseOfEmailAuditLogDto {
  items: Array<EmailAuditLogDto>;
  page: (number | string);
  pageSize: (number | string);
  totalCount: (number | string);
  totalPages?: (number | string);
}
