/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientCompanyDto } from '../models/client-company-dto';
export interface PagedResponseOfClientCompanyDto {
  items: Array<ClientCompanyDto>;
  page: (number | string);
  pageSize: (number | string);
  totalCount: (number | string);
  totalPages?: (number | string);
}
