/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterUserRequest {
  displayName: string;
  email: string;
  providerCompanyId: string;
  role: string;
}
