/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScheduledEmailReceiverDto {
  clientContactEmail: (string | null);
  clientContactId: (string | null);
  clientContactName: (string | null);
  id: string;
  userDisplayName: string;
  userEmail: string;
  userId: string;
}
